packages:
  - app/backend
  - app/frontend

allowBuilds:
  '@google/genai': true
  '@nestjs/core': true
  '@parcel/watcher': true
  '@prisma/engines': true
  bcrypt: true
  canvas: true
  esbuild: true
  msgpackr-extract: true
  prisma: true
  protobufjs: true
  unrs-resolver: true

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@prisma/engines'
  - bcrypt
  - esbuild
  - prisma
  - unrs-resolver
