export enum MareaEstado {
    DESIGNADA = 'DESIGNADA',
    EN_EJECUCION = 'EN_EJECUCION',
    ESPERANDO_ENTREGA = 'ESPERANDO_ENTREGA',
    ENTREGADA_RECIBIDA = 'ENTREGADA_RECIBIDA',
    VERIFICACION_INICIAL = 'VERIFICACION_INICIAL',
    EN_CORRECCION = 'EN_CORRECCION',
    DELEGADA_EXTERNA = 'DELEGADA_EXTERNA',
    PENDIENTE_DE_INFORME = 'PENDIENTE_DE_INFORME',
    ESPERANDO_REVISION = 'ESPERANDO_REVISION',
    PARA_PROTOCOLIZAR = 'PARA_PROTOCOLIZAR',
    ESPERANDO_PROTOCOLIZACION = 'ESPERANDO_PROTOCOLIZACION',
    PROTOCOLIZADA = 'PROTOCOLIZADA',
    CANCELADA = 'CANCELADA'
}
