export type BusinessRules = {
  DIAS_NAVEGADOS_ANUALES: number
  DIAS_DESCANSO_POST_MAREA: number
  DIAS_EXCESO_TIERRA: number
  PLAZO_ENTREGA_DATOS: number
  PLAZO_CONFECCION_INFORME: number
  PLAZO_PROTOCOLIZACION: number
  PLAZO_RECHECK_CORTO: number
  PLAZO_RECHECK_MEDIO: number
  PLAZO_RECHECK_LARGO: number
  UMBRAL_FATIGA_ANUAL_PORCENTAJE: number
  ALERTA_DIAS_CORRIDOS: number
}

export const EMPTY_BUSINESS_RULES: BusinessRules = {
  DIAS_NAVEGADOS_ANUALES: 0,
  DIAS_DESCANSO_POST_MAREA: 0,
  DIAS_EXCESO_TIERRA: 0,
  PLAZO_ENTREGA_DATOS: 0,
  PLAZO_CONFECCION_INFORME: 0,
  PLAZO_PROTOCOLIZACION: 0,
  PLAZO_RECHECK_CORTO: 0,
  PLAZO_RECHECK_MEDIO: 0,
  PLAZO_RECHECK_LARGO: 0,
  UMBRAL_FATIGA_ANUAL_PORCENTAJE: 0,
  ALERTA_DIAS_CORRIDOS: 0,
}
