export const BUSINESS_RULES = {
  DIAS_NAVEGADOS_ANUALES: 180,
  DIAS_DESCANSO_POST_MAREA: 15,
  PLAZO_ENTREGA_DATOS: 15,
  PLAZO_CONFECCION_INFORME: 7,
  PLAZO_PROTOCOLIZACION: 15,
  PLAZO_RECHECK_ALERTAS: 7,
  UMBRAL_FATIGA_ANUAL_PORCENTAJE: 0.9,
  ALERTA_DIAS_CORRIDOS: 60,
} as const
